<!DOCTYPE html><html lang="en-us" >


<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.3.0 for Hugo" />
  

  
  









  




  
  
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    
      
      <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&family=Inconsolata:wght@400;500;600;700&display=swap&display=swap">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&family=Inconsolata:wght@400;500;600;700&display=swap&display=swap" media="print" onload="this.media='all'">
    
  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Gianluca Baio" />

  
  
  
    
  
  <meta name="description" content="This document comments more in details the R script used to perform the whole analysis. Similar results can be obtained using the BUGS interface directly — but as we mentioned in the class, this is usually less efficient and so we focus here on the R script." />

  
  <link rel="alternate" hreflang="en-us" href="/practical/04_ild/solutions/" />

  
  
  
    <meta name="theme-color" content="#1565c0" />
  

  
  
    
    <script src="/js/mathjax-config.js"></script>
  

  

  <link rel="stylesheet" href="/css/vendor-bundle.min.f1ecf783c14edc00c9320c205831ad8e.css" media="print" onload="this.media='all'">

  
  
  
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.1/css/academicons.min.css" integrity="sha512-b1ASx0WHgVFL5ZQhTgiPWX+68KjS38Jk87jg7pe+qC7q9YkEtFq0z7xCglv7qGIs/68d3mAp+StfC8WKC5SSAg==" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    
    
    
    
      
      
    
    
    

    
    
    
      
    
    
      
      
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/github.min.css" crossorigin="anonymous" title="hl-light" media="print" onload="this.media='all'">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/github.min.css" crossorigin="anonymous" title="hl-dark" media="print" onload="this.media='all'" disabled>
      
    

    
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.css" integrity="sha512-1xoFisiGdy9nvho8EgXuXvnpR5GAMSjFwp40gSRE3NwdUdIMIKuPa7bqoUhLD0O/5tPNhteAsE5XyyMi5reQVA==" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.3ef10ad94e43ba7ad3f08b0b007578ae.css" />

  



  

  

  




  
  
  

  

  
    <link rel="manifest" href="/manifest.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hu62751289ff52b250e581ec75f909b74a_9702_32x32_fill_lanczos_center_3.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hu62751289ff52b250e581ec75f909b74a_9702_180x180_fill_lanczos_center_3.png" />

  <link rel="canonical" href="/practical/04_ild/solutions/" />

  
  
  
  
  
  
  
  
    
    
  
  

  
  
    
    
  
  <meta property="twitter:card" content="summary" />
  
  <meta property="og:site_name" content="Bayesian methods in health economics" />
  <meta property="og:url" content="/practical/04_ild/solutions/" />
  <meta property="og:title" content="Practical 4. Cost-effectiveness analysis with individual level data — SOLUTIONS | Bayesian methods in health economics" />
  <meta property="og:description" content="This document comments more in details the R script used to perform the whole analysis. Similar results can be obtained using the BUGS interface directly — but as we mentioned in the class, this is usually less efficient and so we focus here on the R script." /><meta property="og:image" content="/media/logo_hu1963fc62d5b8fe503cce6274f5cb00c3_9765_300x300_fit_lanczos_3.png" />
    <meta property="twitter:image" content="/media/logo_hu1963fc62d5b8fe503cce6274f5cb00c3_9765_300x300_fit_lanczos_3.png" /><meta property="og:locale" content="en-us" />
  
    
      <meta
        property="article:published_time"
        content="2022-06-21T10:00:00&#43;00:00"
      />
    
    <meta property="article:modified_time" content="2022-06-21T10:00:00&#43;00:00">
  

  



  

  

  





  <title>Practical 4. Cost-effectiveness analysis with individual level data — SOLUTIONS | Bayesian methods in health economics</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper   " data-wc-page-id="29de051086a250951138b573887259ab" >

  
  
  
  
  
  
  
  
  
  <script src="/js/wowchemy-init.min.da42964e270e05a6063fbca894d7ccff.js"></script>

  




  <div class="page-header">
    











  


<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/"><img src="/media/logo_hu1963fc62d5b8fe503cce6274f5cb00c3_9765_0x70_resize_lanczos_3.png" alt="Bayesian methods in health economics"
          
          ></a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/"><img src="/media/logo_hu1963fc62d5b8fe503cce6274f5cb00c3_9765_0x70_resize_lanczos_3.png" alt="Bayesian methods in health economics"
        
        ></a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#timetable"><span>Timetable</span></a>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Slides</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/slides/01_Intro"><span>Introduction</span></a>
            
              <a class="dropdown-item" href="/slides/02_MCMC"><span>Bayesian computation</span></a>
            
              <a class="dropdown-item" href="/slides/03_Intro_HE"><span>Introduction to Health Economics</span></a>
            
              <a class="dropdown-item" href="/slides/04_ILD"><span>Individual level data</span></a>
            
              <a class="dropdown-item" href="/slides/05_ALD"><span>Aggregated level data</span></a>
            
              <a class="dropdown-item" href="/slides/06_NMA"><span>Network meta-analysis</span></a>
            
              <a class="dropdown-item" href="/slides/07_Model_uncertainty"><span>Model error and structural analysis</span></a>
            
              <a class="dropdown-item" href="/slides/08_Survival"><span>Survival modelling in HTA</span></a>
            
              <a class="dropdown-item" href="/slides/09_MM"><span>Markov models</span></a>
            
              <a class="dropdown-item" href="/slides/10_Missing"><span>Missing data in HTA</span></a>
            
              <a class="dropdown-item" href="/slides/11_VoI"><span>Introduction to Value of information</span></a>
            
              <a class="dropdown-item" href="/slides/12_EVPPI"><span>Expected value of partial information</span></a>
            
              <a class="dropdown-item" href="/syllabus/lecture13/13_EVSI.pdf"><span>Expected value of sample information</span></a>
            
              <a class="dropdown-item" href="/syllabus/lecture14/14_Data_EVSI.pdf"><span>Generating data for the analysis of the EVSI</span></a>
            
              <a class="dropdown-item" href="/syllabus/lecture15/15_EVSI_MC.pdf"><span>Calculating expected value of sample information</span></a>
            
              <a class="dropdown-item" href="/syllabus/lecture16/16_EVSI_regression.pdf"><span>Regression-based EVSI</span></a>
            
          </div>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Practicals</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/practical/01_monte-carlo"><span>Monte Carlo</span></a>
            
              <a class="dropdown-item" href="/practical/02_mcmc"><span>MCMC</span></a>
            
              <a class="dropdown-item" href="/practical/03_bcea"><span>Cost-effectiveness analysis</span></a>
            
              <a class="dropdown-item" href="/practical/04_ild"><span>HTA with individual level data</span></a>
            
              <a class="dropdown-item" href="/practical/05_ald"><span>Evidence synthesis and decision models</span></a>
            
              <a class="dropdown-item" href="/practical/06_nma"><span>NMA</span></a>
            
              <a class="dropdown-item" href="/practical/07_structural"><span>PSA to structural uncertainty</span></a>
            
              <a class="dropdown-item" href="/practical/08_survival"><span>Survival analysis</span></a>
            
              <a class="dropdown-item" href="/practical/09_mm"><span>Markov and multistate models</span></a>
            
              <a class="dropdown-item" href="/practical/10_missing"><span>Missing data</span></a>
            
              <a class="dropdown-item" href="/practical/11_intro_voi"><span>Computing the EVPI using Monte Carlo</span></a>
            
              <a class="dropdown-item" href="/practical/12_evppi"><span>Computing the EVPPI in BCEA and SAVI</span></a>
            
              <a class="dropdown-item" href="/practical/13_data_evsi"><span>Generating data for the EVSI</span></a>
            
              <a class="dropdown-item" href="/practical/14_evsi_mc"><span>Computing the EVSI using Monte Carlo</span></a>
            
              <a class="dropdown-item" href="/practical/15_evsi_regression"><span>Computing the EVSI using regression</span></a>
            
          </div>
        </li>

        
        

        
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"><span>Instructions</span><span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            
              <a class="dropdown-item" href="/tips/computer-specification"><span>Computer specification</span></a>
            
              <a class="dropdown-item" href="/tips/using-bugs"><span>Using BUGS</span></a>
            
          </div>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/publication"><span>Reading list</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#people"><span>People</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      
        
      
        
      
        
      
        
      

      
      

      
      

      
      

    </ul>

  </div>
</nav>


  </div>

  <div class="page-body">
    

<div class="container-fluid docs">
  <div class="row flex-xl-nowrap">
    <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
      <form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-md-3 w-100" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <div class="d-flex">
      <span class="d-md-none pl-1 flex-grow-1 text-left overflow-hidden">
        
          4. ILD
        
      </span>
      <span><i class="fas fa-chevron-down"></i></span>
    </div>
  </button>

  
</form>

<nav class="collapse docs-links" id="docs-nav">
  
  
  
  
  
  

  
  
    

    
      

      


  
    
    
    
    
      
    
    

    
      <ul class="nav docs-sidenav">
        <li class=""><a href="/practical/"></a></li>
    
      


  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/01_monte-carlo/">1. Monte Carlo</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/01_monte-carlo/solutions/">Solutions</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/02_mcmc/">2. MCMC</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/02_mcmc/solutions/">Solutions</a></li>



  <li class=""><a href="/practical/02_mcmc/covid/">Covid</a></li>



  <li class=""><a href="/practical/02_mcmc/tutorial/">MCMC Tutorial</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/03_bcea/">3. Intro-HE</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/03_bcea/solutions/">Solution</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/04_ild/">4. ILD</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/04_ild/tutorial-regression/">Regression Tutorial</a></li>



  <li class="active"><a href="/practical/04_ild/solutions/">Solutions</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/05_ald/">5. ALD</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/05_ald/solutions/">Solutions</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/06_nma/">6. NMA</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/06_nma/solutions/">Solutions</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/07_structural/">7. PSA to structural uncertainty</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/07_structural/solutions/">Solutions</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/08_survival/">8. Survival</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/08_survival/solutions/">Solutions</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/09_mm/">9. Markov models</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/09_mm/solutions/">Solutions</a></li>



  <li class=""><a href="/practical/09_mm/cohort-model/">Cohort discrete Markov model</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/10_missing/">10. Missing data</a>
    
      
        <ul class="nav docs-sidenav">
      


  <li class=""><a href="/practical/10_missing/solutions/">Solutions</a></li>

      
        </ul>
      
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/11_intro_voi/">11. EVPI using MC</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/12_evppi/">12. EVPPI in BCEA &amp; SAVI</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/13_data_evsi/">13 Generating data for EVSI</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/14_evsi_mc/">14. EVSI using MC</a>
    

    
      </div>
    



  
    
    
    
    
      
    
    

    
      <div class="docs-toc-item">
        <a class="docs-toc-link " href="/practical/15_evsi_regression/">15. EVSI using regression</a>
    

    
      </div>
    

      
    

    
      </ul>
    

  
</nav>
    </div>

    <main class="col-10 docs-content" role="main">
      <article class="article">

        <div class="docs-article-container">
          <h1>Practical 4. Cost-effectiveness analysis with individual level data — SOLUTIONS</h1>
          
          
          
          
          




<div class="btn-links mb-3">
  
  








  


















  
  
  
    
  
  
  
  
  
    
    
      
    
  
  <a class="btn btn-outline-primary btn-page-header" href="/slides/04_ILD" >
    Lecture 4</a>

  
  
  
    
  
  
  
  
  
    
    
      
    
  
  <a class="btn btn-outline-primary btn-page-header" href="/practical/04_ild/solutions4.pdf" >
    <i class="fas fa-file-pdf mr-1"></i>PDF version</a>


</div>


          <br>
          
          <div class="article-style">
            


<p>This document comments more in details the <tt>R</tt> script used to perform
the whole analysis. Similar results can be obtained using the <tt>BUGS</tt>
interface directly — but as we mentioned in the class, this is usually
less efficient and so we focus here on the <tt>R</tt> script.</p>
<p>The first thing to do is to make sure that you are in the correct
folder. You can check the location of your
<tt>R</tt> workspace by typing the following command</p>
<pre class="r"><code>getwd()</code></pre>
<p>which would return something like</p>
<pre class="r"><code>[1] &quot;/home/gianluca&quot;</code></pre>
<p>— the symbol <code>[1]</code> here indicates the the answer is a vector and the
current rows starts with its first (and, in this case, only) element.</p>
<p>You can move to different directories by using a command like the
following</p>
<pre class="r"><code>setwd(&quot;/home/gianluca/Mystuff&quot;)</code></pre>
<p>which, in this case, would move the workspace in the subfolder
<code>Mystuff</code>. In <code>Rstudio</code> you can also use the menus under <code>Session</code> to
move across the folders on your computer.</p>
<p>The next step is to load in the <tt>R</tt> workspace
the relevant “packages”. In this case, this is done using the following
command (that are typeset in red).</p>
<pre class="r"><code>library(R2OpenBUGS)</code></pre>
<p>You can of course load any other package you require at any point in
your script.</p>
<div id="question-1" class="section level2">
<h2>Question 1</h2>
<p>We now proceed to load the data on costs, using the following
<tt>R</tt> command (here the hash symbol “<code>#</code>” indicates a comment)</p>
<pre class="r"><code># Loads the data on costs only into R from the txt file (list originally prepared for BUGS)
cost.data=source(&quot;cost-data.txt&quot;)$value</code></pre>
<p>The <tt>R</tt> command <code>source</code> executes into the
<tt>R</tt> workspace the commands included in the file
that is used as its argument. In this case, the file <code>cost-data.txt</code>
contains a <em>list</em> of values for a set of different variables and the
above comment assigns this list to a new
<tt>R</tt> variable named <code>cost.data</code>. Notice here
that we also add the suffix <code>$value</code> to the <code>source</code> command. The reason
for this is that in this way, <tt>R</tt> can strip the
values for the elements of the list contained in the <code>.txt</code> file from
all the “meta-data”” (i.e. external information that is irrelevant to
us). For example, compare the following output</p>
<pre class="r"><code>cost.data=source(&quot;cost-data.txt&quot;)$value
names(cost.data)</code></pre>
<pre><code>[1] &quot;N1&quot;    &quot;N2&quot;    &quot;cost1&quot; &quot;cost2&quot;</code></pre>
<p>with the one obtained by omitting the <code>$value</code> suffix.</p>
<pre class="r"><code>cost.data=source(&quot;cost-data.txt&quot;)
names(cost.data)</code></pre>
<pre><code>[1] &quot;value&quot;   &quot;visible&quot;</code></pre>
<pre class="r"><code>names(cost.data$value)</code></pre>
<pre><code>[1] &quot;N1&quot;    &quot;N2&quot;    &quot;cost1&quot; &quot;cost2&quot;</code></pre>
<p>In the first case, the elements of the object <code>cost.data</code> are the
variables that we need to use as data for the
<span><span><tt>BUGS</tt></span></span>model. In the second one, these are
actually “hidden” inside the object <code>values</code> that is stored inside the
object <code>cost.data</code>.</p>
<p>We are now ready to start setting everything up to run
<span><span><tt>BUGS</tt></span></span>remotely from our
<tt>R</tt> session. The first things to do are to
define the relevant inputs to the <tt>BUGS</tt> function that will do just
that.</p>
<pre class="r"><code># Runs the BUGS model from R
model.file=&quot;normal-mod.txt&quot;
params &lt;- c(&quot;mu&quot;,&quot;ss&quot;,&quot;ls&quot;,&quot;delta.c&quot;,&quot;dev&quot;,&quot;total.dev&quot;)
n.chains=2
n.burnin=1000
n.iter=2000
n.thin=1
debug=FALSE</code></pre>
<ul>
<li><p>The first command here defines a string with the path to the file in
which we have saved the model code. This will instruct
<span><span><tt>BUGS</tt></span></span>about where to read the
model assumptions.</p></li>
<li><p>The second line defines the parameters to be monitored and stores
them (as strings of names) into the vector <code>params</code> — of course you
can use any naming convention you like; so this vector may be called
<code>parameters</code>, or <code>x</code> instead.</p></li>
<li><p>The third line defines a numeric variable in which we specify the
number of Markov chains we want to run — in this case 2. It is
usually a good idea to run more than one chain, because by starting
them from different initial values, this helps assessing convergence
to the target posterior distributions of all the relevant variables
in our model.</p></li>
<li><p>The fourth line defines the number of iterations to be used as
“burn-in”, i.e. to get closer to the core of the target
posterior distributions. In this case, we are selecting 1000 — there
is no reason why 1000 should <em>always</em> be sufficient, so we should
assess convergence very carefully (more on this later).</p></li>
<li><p>The fifth line defines the total number of simulations to be run,
which will be used to obtain the samples that we will use for the
analysis after discarding the burn-in. In this case, we set
<code>n.iter</code>=2000, which means that, in total, we will run the MCMC for
<span class="math inline">\(2\times(2000)=4000\)</span> simulations (because we have selected
2 chains). Of these, the first <span class="math inline">\(2\times 1000=2000\)</span> will be discarded
as burn-in, which means that the summary statistics will be computed
on a sample of <span class="math inline">\(2000\)</span> simulations.</p></li>
<li><p>The sixth line defines the “thinning” of the chains. In this case,
<code>n.thin</code>=1, which means that we are actually storing every single
iteration after the burn-in for our analysis. In general,
<span><span><tt>BUGS</tt></span></span>will save 1 every <code>n.thin</code>
simulations, so using a thinning level above 1 means that some of
the simulations will be discarded (and consequently, to have the
same overall sample size we will need a longer run of the MCMC).
This may help reduce autocorrelation in our results (see the lecture
slides and both <em>BMHE</em> and <em>The BUGS Book</em>, for more details).</p></li>
<li><p>Finally, the seventh line defines a logical variable <code>debug</code>. In
this case we set it to the value <code>FALSE</code>, which means that
<span><span><tt>BUGS</tt></span></span>will be called remotely and we will
not see it in action. If we set <code>debug=TRUE</code>, then
<span><span><tt>BUGS</tt></span></span>would forcibly take over from
<tt>R</tt> and we would see it opening its windows
and spitting out its output. This works <strong>under <code>MS Windows</code> only</strong>.</p></li>
</ul>
<p>At this point we are finally ready to call
<span><span><tt>BUGS</tt></span></span>, which we do using the following
command.</p>
<pre class="r"><code>m=bugs(data=cost.data,inits=NULL,model.file=model.file,parameters.to.save=params,
       n.chains=n.chains,n.iter=n.iter,n.burnin=n.burnin,n.thin=n.thin,DIC=T,debug=debug)</code></pre>
<p>The model is run by <span><span><tt>BUGS</tt></span></span>and while this is
happening, we lose access to the <tt>R</tt> session
(i.e. you cannot use <tt>R</tt> to make other
calculations while <span><span><tt>BUGS</tt></span></span>is running). When
<span><span><tt>BUGS</tt></span></span>is finished, then
<tt>R</tt> takes over again and if everything has
worked, the object <code>m</code> is stored in our workspace. We can inspect it by
using the following command.</p>
<pre class="r"><code>names(m)</code></pre>
<pre><code> [1] &quot;n.chains&quot;        &quot;n.iter&quot;          &quot;n.burnin&quot;        &quot;n.thin&quot;         
 [5] &quot;n.keep&quot;          &quot;n.sims&quot;          &quot;sims.array&quot;      &quot;sims.list&quot;      
 [9] &quot;sims.matrix&quot;     &quot;summary&quot;         &quot;mean&quot;            &quot;sd&quot;             
[13] &quot;median&quot;          &quot;root.short&quot;      &quot;long.short&quot;      &quot;dimension.short&quot;
[17] &quot;indexes.short&quot;   &quot;last.values&quot;     &quot;isDIC&quot;           &quot;DICbyR&quot;         
[21] &quot;pD&quot;              &quot;DIC&quot;             &quot;model.file&quot;     </code></pre>
<p>There are many variables inside the object <code>m</code> and we can use the “$”
operator in <tt>R</tt> to access them. For example,
the command</p>
<pre class="r"><code>m$n.sims</code></pre>
<pre><code>[1] 2000</code></pre>
<p>returns the total number of simulations used by
<span><span><tt>BUGS</tt></span></span>to compute the posterior distributions.</p>
<p>The first thing to do once the model has run is to check the summary
statistics for the posterior distributions, together with the
convergence diagnostics. We can do this using the <code>print</code> function. For
example, the command</p>
<pre class="r"><code>print(m,digits=2)</code></pre>
<pre><code>Inference for Bugs model at &quot;normal-mod.txt&quot;, 
Current: 2 chains, each with 2000 iterations (first 1000 discarded)
Cumulative: n.sims = 2000 iterations saved
             mean    sd    2.5%     25%     50%     75%   97.5% Rhat n.eff
mu[1]       22.72  1.18   20.46   21.90   22.71   23.51   25.10    1  2000
mu[2]       24.53  1.28   22.09   23.69   24.52   25.39   27.12    1  2000
ss[1]      486.18 38.60  418.00  459.65  483.50  509.12  568.61    1  2000
ss[2]      550.47 41.47  477.48  520.80  548.55  576.90  634.80    1  2000
ls[1]        3.09  0.04    3.02    3.06    3.09    3.12    3.17    1  2000
ls[2]        3.15  0.04    3.08    3.13    3.15    3.18    3.23    1  2000
delta.c      1.81  1.74   -1.62    0.63    1.83    3.04    5.06    1  2000
dev[1]    2995.63  2.02 2994.00 2994.00 2995.00 2996.00 3001.00    1  1900
dev[2]    3064.17  2.07 3062.00 3063.00 3064.00 3065.00 3070.00    1  2000
total.dev 6059.77  2.81 6056.00 6058.00 6059.00 6061.00 6067.00    1  2000
deviance  6059.77  2.81 6056.00 6058.00 6059.00 6061.00 6067.00    1  2000

For each parameter, n.eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor (at convergence, Rhat=1).

DIC info (using the rule, pD = Dbar-Dhat)
pD = 3.90 and DIC = 6064.00
DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
<p>shows the summary table for the nodes (variables) we have chosen to
monitor. The optional input <code>digits=2</code> instructs
<tt>R</tt> to show the results using 2 significant
figures. The table reports the mean, standard deviation and selected
quantiles of the posterior distributions. We can typically use the 2.5%
and the 97.5% quantiles to approximate a 95% <em>credible</em> interval. In
addition, the table reports the values for <span class="math inline">\(\hat{R}\)</span>, the potential
scale reduction (or Gelman-Rubin statistic) and the effective sample
size (<code>n.eff</code>) — see the lecture slides and both <em>BMHE</em> and <em>The BUGS
Book</em>, for more details.</p>
<p>Given this analysis, the mean cost is 22.72 for the control arm and
24.53 for the intervention arm. The mean difference in costs is 1.81 —
recall that costs are entered in
<span><span><tt>BUGS</tt></span></span><span class="math inline">\(\times 1000\)</span>. We can also manipulate
the simulations to produce further analyses. For example, we can use the
code</p>
<pre class="r"><code>plot(
    m$sims.list$mu[,1],
    m$sims.list$mu[,2],
    xlab=&quot;Population average cost in arm 1 (x 1000)&quot;,
    ylab=&quot;Population average cost in arm 2 (x 1000)&quot;,
    pch=20,
    cex=.6,
    main=&quot;Joint distribution of mean costs&quot;
)</code></pre>
<p>to display (in the graph below) the posterior joint distribution of the
population average costs in the two arms (the
<tt>R</tt> script provided for the practical provides
also some description of the graphical parameters used in this call).</p>
<p>Notice again the use of the “$” operator to access elements of the
object <code>m</code>. In this case, the element <code>sims.list</code> is a list containing
<code>all</code> the simulated values for all the monitored nodes. You can actually
inspect them with the following code.</p>
<pre class="r"><code>names(m$sims.list)</code></pre>
<pre><code>[1] &quot;mu&quot;        &quot;ss&quot;        &quot;ls&quot;        &quot;delta.c&quot;   &quot;dev&quot;       &quot;total.dev&quot;
[7] &quot;deviance&quot; </code></pre>
<pre class="r"><code>head(m$sims.list$mu[,1])</code></pre>
<pre><code>[1] 21.77 23.83 20.31 22.58 23.79 23.76</code></pre>
<p>The <tt>R</tt> command <code>head</code> shows by default the
first 6 values of a variable.</p>
<p><img src="/practical/04_ild/solutions_files/figure-html/inspectBUGS44-1.png" width="460.8" style="display: block; margin: auto;" /></p>
<p>Notice here the interesting fact that
<span><span><tt>BUGS</tt></span></span>effectively adds a dimension to each
node. So the node <code>mu</code> is defined in the model code as a vector with 2
values (one for arm 1 and the other for arm 2). But because when
processed by <span><span><tt>BUGS</tt></span></span>we record for each of these
two elements <code>n.sims</code> simulations, then the resulting object turns into
a matrix with <code>n.sims</code> = 2000 rows and 2 columns. So, in reference to
the code used to generate the plot of the joint distribution of the mean
costs, <code>m$sims.list$mu[,1]</code> indicates all the rows and the first column
and <code>m$sims.list$mu[,2]</code> indicates all the rows and the second column of
the matrix <code>m$mu</code>.</p>
</div>
<div id="question-2" class="section level2">
<h2>Question 2</h2>
<p>We have already included in the vector <code>params</code> the nodes related to the
deviance — these are <code>dev</code> and <code>total.dev</code>, which are coded in the
<span><span><tt>BUGS</tt></span></span>model to compute manually the deviance
associated with the underlying Normal model. In practice you do not need
to do this and <span><span><tt>BUGS</tt></span></span>will calculate (and
monitor) the deviance automatically — assuming that there is at least
one observed variable (you can think of why this is!).</p>
<p>Going back to the summary statistics table, we can see that the overall
model deviance is, on average, 6059.77. This is the same value, whether
computed manually (in the node <code>total.dev</code>) or automatically (in the
node <code>deviance</code>).</p>
</div>
<div id="question-3" class="section level2">
<h2>Question 3</h2>
<p>The first thing to do now is to load the new dataset, which includes
data on costs as well as utilities. Then we can setup our call to
<span><span><tt>BUGS</tt></span></span>pointing to the correct model file.
Finally, because this new model (based on Gamma-Gamma structure — see
the lecture slides) is more complex, we need to provide
<span><span><tt>BUGS</tt></span></span>with a set of suitable initial values
(identified using a trial-and-error procedure). We do this using the
following <tt>R</tt> commands.</p>
<pre class="r"><code># Loads the data on costs only into R from the txt file (list originally prepared for BUGS)
cost.utility=source(&quot;cost-util-data.txt&quot;)$value

# Specifies the new model file
model.file=&quot;cgeg-mod.txt&quot;

# Loads the 3 sets of initial values from the .txt files
inits1=source(&quot;cgeg-inits1.txt&quot;)$value
inits2=source(&quot;cgeg-inits2.txt&quot;)$value
inits3=source(&quot;cgeg-inits3.txt&quot;)$value
# And combines them into a single list
inits=list(inits1,inits2,inits3)

# Re-defines the list of parameters to be monitored
params=c(&quot;mu.c&quot;,&quot;mu.e&quot;,&quot;delta.c&quot;,&quot;delta.e&quot;,&quot;shape.c&quot;,&quot;shape.e&quot;,&quot;beta&quot;,&quot;INB&quot;,&quot;CEAC&quot;)

# Re-defines the burn-in, number of simulations and number of chains
n.burnin=1000
n.iter=4000         # NB: this adds 3000 simulations to the 1000 of burnin
n.chains=3</code></pre>
<p>Notice that we need to be consistent in the definition of the number of
chains and the set up of the <code>inits</code>. So if we select 3 chains, then
<code>inits</code> needs to be a list comprising of 3 lists (as in this case) —
failure to do this will result in
<tt>R</tt> complaining and stopping with an error
message.</p>
<p>After that, we are ready to call <span><span><tt>BUGS</tt></span></span>and run
the new model, which we do using the following command.</p>
<pre class="r"><code>m2=bugs(data=cost.utility,inits=inits,model.file=model.file,parameters.to.save=params,
    n.chains=n.chains,n.iter=n.iter,n.burnin=n.burnin,n.thin=n.thin,DIC=T,debug=debug)</code></pre>
<p>The results can be again printed in the form of a summary table.</p>
<pre class="r"><code>print(m2,digits=2)</code></pre>
<pre><code>Inference for Bugs model at &quot;cgeg-mod.txt&quot;, 
Current: 3 chains, each with 4000 iterations (first 1000 discarded)
Cumulative: n.sims = 9000 iterations saved
              mean    sd    2.5%     25%     50%     75%   97.5% Rhat n.eff
mu.c[1]      23.47  1.99   20.02   22.09   23.31   24.69   27.83    1   700
mu.c[2]      25.99  2.02   22.47   24.57   25.84   27.24   30.38    1  3000
mu.e[1]      74.70  7.13   61.77   69.81   74.28   79.17   90.15    1  1300
mu.e[2]      81.05  8.14   66.62   75.26   80.63   86.45   97.78    1  6100
delta.c       2.52  2.80   -3.02    0.66    2.55    4.38    7.94    1   660
delta.e      -6.34 10.74  -27.39  -13.84   -6.27    1.02   14.81    1  1800
shape.c[1]    1.18  0.09    1.01    1.12    1.18    1.24    1.36    1  3300
shape.c[2]    1.67  0.13    1.43    1.58    1.67    1.76    1.95    1  9000
shape.e[1]    0.41  0.03    0.35    0.39    0.41    0.43    0.46    1  9000
shape.e[2]    0.37  0.03    0.32    0.36    0.37    0.39    0.43    1  9000
beta[1]       0.16  0.02    0.12    0.14    0.16    0.18    0.21    1  1100
beta[2]       0.17  0.02    0.13    0.15    0.17    0.18    0.21    1  3100
INB[1]       -2.52  2.80   -7.94   -4.38   -2.55   -0.66    3.02    1   660
INB[2]       -3.15  3.57  -10.17   -5.55   -3.18   -0.74    3.81    1   730
INB[3]       -3.79  4.46  -12.59   -6.81   -3.82   -0.74    4.87    1   810
INB[4]       -4.42  5.43  -14.98   -8.15   -4.41   -0.68    6.01    1   900
INB[5]       -5.06  6.42  -17.57   -9.50   -5.05   -0.62    7.23    1   970
INB[6]       -5.69  7.44  -20.19  -10.84   -5.68   -0.61    8.70    1  1000
INB[7]       -6.33  8.47  -23.01  -12.18   -6.36   -0.54   10.07    1  1100
INB[8]       -6.96  9.51  -25.67  -13.52   -6.93   -0.46   11.42    1  1100
INB[9]       -7.59 10.56  -28.38  -14.90   -7.60   -0.39   12.83    1  1200
INB[10]      -8.23 11.61  -31.06  -16.23   -8.20   -0.27   14.26    1  1200
INB[11]      -8.86 12.67  -33.72  -17.60   -8.83   -0.18   15.60    1  1300
CEAC[1]       0.18  0.39    0.00    0.00    0.00    0.00    1.00    1   680
CEAC[2]       0.19  0.39    0.00    0.00    0.00    0.00    1.00    1   810
CEAC[3]       0.20  0.40    0.00    0.00    0.00    0.00    1.00    1   910
CEAC[4]       0.21  0.41    0.00    0.00    0.00    0.00    1.00    1  1200
CEAC[5]       0.22  0.41    0.00    0.00    0.00    0.00    1.00    1  1300
CEAC[6]       0.23  0.42    0.00    0.00    0.00    0.00    1.00    1  2200
CEAC[7]       0.23  0.42    0.00    0.00    0.00    0.00    1.00    1  2800
CEAC[8]       0.23  0.42    0.00    0.00    0.00    0.00    1.00    1  2600
CEAC[9]       0.24  0.43    0.00    0.00    0.00    0.00    1.00    1  2000
CEAC[10]      0.24  0.43    0.00    0.00    0.00    0.00    1.00    1  2200
CEAC[11]      0.24  0.43    0.00    0.00    0.00    0.00    1.00    1  2300
deviance   9756.35  4.44 9750.00 9753.00 9756.00 9759.00 9766.00    1  2600

For each parameter, n.eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor (at convergence, Rhat=1).

DIC info (using the rule, pD = Dbar-Dhat)
pD = 9.93 and DIC = 9766.00
DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
<p>As is possible to see, all values for <span class="math inline">\(\hat{R}\)</span> are essentially 1,
indicating that the model has converged. Autocorrelation is somewhat
large, as confirmed by the fact that the effective sample size is
relatively small in comparison to the actual sample size (9000
simulations) for many if not all the nodes. In real-world analyses, this
would grant further analysis — for example by inspecting the traceplots
of the nodes and possibly running the model for longer or using thinning
(see <em>BMHE</em>, chapter 4 for <tt>R</tt> code to create
traceplots).</p>
<p>The next part consists in manipulating the object <code>m2</code> in order to
obtain more advanced analyses. Notice that in fact, we can use <code>BCEA</code> to
do all these, but for the sake of practice, we use our own
<tt>R</tt> code, in this case.</p>
<p>The first thing to do is a cost-effectiveness plot. Recall that this is
obtained by plotting the joint distribution of <span class="math inline">\(\Delta_e,\Delta_c\)</span>.
Thus, it is sufficient to access the nodes <code>delta.e</code> and <code>delta.c</code>
inside the object <code>m2</code> and the <tt>R</tt> function
<code>plot</code>, as shown below.</p>
<pre class="r"><code>plot(m2$sims.list$delta.e,m2$sims.list$delta.c,pch=20,cex=.8,xlab=&quot;Effectiveness differential&quot;,
    ylab=&quot;Cost differential&quot;,main=&quot;Cost-effectiveness plane&quot;)
abline(v=0,lwd=2,col=&quot;gray&quot;)
abline(h=0,lwd=2,col=&quot;gray&quot;)</code></pre>
<p><img src="/practical/04_ild/solutions_files/figure-html/inspectBUGS7-1.png" width="460.8" style="display: block; margin: auto;" /></p>
<p>The command <code>abline</code> can be used to add a line to the graph. The input
<code>v=0</code> indicates a vertical line at 0, while the input <code>h=0</code> specifies a
horizontal line at 0. The extra parameters <code>lwd</code> and <code>col</code> specify the
width of the line and the color used, respectively (you can use
<code>help(plot)</code> and <code>help(colours)</code> in your
<tt>R</tt> terminal to get more information).</p>
<p>We can use this graph to assess the uncertainty around the overall
cost-effectiveness analysis; for example, we can visually assess the
proportion of points lying in each of the four quadrants — for instance,
the vast majority seems to be in the NW quadrant, where the new
intervention is more expensive and less effective.</p>
<p>Next we turn to the analysis of the Incremental Net Benefit (INB). We
are asked to assess its value for a willingness to pay of
<span class="math inline">\(k=\)</span>£500. So, using the code provided in the model file, we
can use the following <tt>R</tt> commands to identify
the corresponding index.</p>
<pre class="r"><code>K=numeric()
K.space=0.1
for (j in 1:11) {
    K[j]=(j-1)*K.space
}
idx=which(K==0.5)</code></pre>
<p>Firstly, we recreate in the <tt>R</tt> workspace the
vector of possible willingness to pay thresholds, <code>K</code>. Unlike
<span><span><tt>BUGS</tt></span></span>, <tt>R</tt> requires
us to define any non-scalar quantity before we can use it, e.g. inside a
loop. We can do this using the command <code>K=numeric()</code>, which effectively
creates a new variable <code>K</code> and tells <tt>R</tt> to
expect a numeric vector (which can also be length 1, i.e. be a scalar).
Next, we set the step of 0.1 (=£100) in the variable <code>K.space</code> and use
it to fill in the vector <code>K</code>. Notice that in
<tt>R</tt> we create loops using the <code>for</code> function,
which takes as arguments</p>
<ul>
<li><p>the index (in this case <code>j</code>);</p></li>
<li><p>the starting point (in this case 1);</p></li>
<li><p>the ending point (in this case 11).</p></li>
</ul>
<p>The <tt>R</tt> notation is fairly straightforward as
basically instructs the computer to move <code>j</code> “in 1 to 11” — this means
that <tt>R</tt> will repeat the commands specified
inside the loop (delimited by the two curly brackets “{” and “}”) upon
varying the index <code>j</code> from 1 to 2, 3, …, 11.</p>
<p>The resulting vector is</p>
<pre class="r"><code>K</code></pre>
<pre><code> [1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0</code></pre>
<p>and the variable <code>idx</code> is computed as the element of <code>K</code> that is exactly
equal to 0.5, as defined in the function <code>which</code> above. Notice that in
logical functions (e.g. <code>if</code>, <code>while</code>, <code>which</code>),
<tt>R</tt> requires that the equality condition is
represented by “<code>==</code>” (notice the double sign of equality).</p>
<p>At this point, we can use the <tt>R</tt> built-in
functions <code>mean</code> and <code>quantile</code> to estimate the average and 95% interval
for the INB at <span class="math inline">\(k=\mbox{\pounds}500\)</span>. We can do this using the following
commands.</p>
<pre class="r"><code>mean(m2$sims.list$INB[,idx])</code></pre>
<pre><code>[1] -5.691401</code></pre>
<pre class="r"><code>quantile(m2$sims.list$INB[,idx],.025)</code></pre>
<pre><code>     2.5% 
-20.19075 </code></pre>
<pre class="r"><code>quantile(m2$sims.list$INB[,idx],.975)</code></pre>
<pre><code>  97.5% 
8.70215 </code></pre>
<p>Notice again that <code>INB</code> is defined as a vector in the
<span><span><tt>BUGS</tt></span></span>model (with one value for each value of
<code>K</code>). This means that resulting object from the
<span><span><tt>BUGS</tt></span></span>simulations is turned into a matrix
(increased by one dimension) and what we need is to access all the rows
of the <code>idx</code>-th column (which is associated with
<span class="math inline">\(k=\mbox{\pounds}500\)</span>).</p>
<p>We can manipulate the simulation further to obtain an estimate of the
probability that the INB is positive at this threshold. This can be
easily obtained by computing the proportion of simulations for which
this is true, which we do using the following command.</p>
<pre class="r"><code>sum(m2$sims.list$INB[,idx]&gt;0)/m2$n.sims</code></pre>
<pre><code>[1] 0.227</code></pre>
<p>The logical expression <code>m2$sims.list$INB[,idx]&gt;0</code> checks whether each of
the <code>m2$n.sims</code> simulations in the <code>idx</code>-th column of the matrix
<code>m2$sims.list$INB</code> is positive. If so, it returns a 1, while if not, it
will return a 0. Thus to sum over all these 1s and 0s and then divide by
the total number of simulations, will provide an estimate of the
probability that INB is positive.</p>
<p>Finally, we can compute and plot the Cost-Effectiveness Acceptability
Curve (CEAC), using the following code.</p>
<pre class="r"><code>CEAC=numeric()
for (i in 1:length(K)) {
    CEAC[i]=mean(m2$sims.list$CEAC[,i]) 
}
plot(K,CEAC,xlab=&quot;Willingness to pay (x 1000)&quot;,ylab=&quot;Cost-effectiveness acceptability curve&quot;,
     main=&quot;&quot;,t=&quot;l&quot;)</code></pre>
<p><img src="/practical/04_ild/solutions_files/figure-html/inspectBUGS12-1.png" width="460.8" style="display: block; margin: auto;" /></p>
<p>Firstly, recall that the CEAC is in fact the probability that INB is
positive, for each selected value of the willingness to pay. So we
define a vector <code>CEAC</code>, in which we want to store the best estimate
(i.e. the mean of the posterior distribution) from our model. To do
this, we create a <code>for</code> loop. Notice that this time, we are being a bit
clever and instead of specifying the ending point of the loop, we let
<tt>R</tt> compute it itself by defining it equal to
<code>length(K)</code> — that is, obviously, the length of the vector <code>K</code>.</p>
<p>Once the vector <code>CEAC</code> has been filled in, we can simply plot it agains
the values of the willingness to pay using the <code>plot</code> function. Notice
that, by default, <code>plot</code> uses open dots to display the selected values.
To overwrite this behaviour, we need to specify the option <code>t=l</code>, which
instructs <tt>R</tt> to use a line (curve) instead.</p>
<p>We can link the CEAC with the Cost-Effectiveness plane by noticing that the former is essentially the proportion of “futures” (i.e. simulated points in the latter) that lie below the line <span class="math inline">\(\Delta_e=k\Delta_c\)</span>, for a given willingness to pay threshold, <span class="math inline">\(k\)</span>.</p>
<p><img src="/practical/04_ild/solutions_files/figure-html/inspectBUGS13-1.png" width="460.8" style="display: block; margin: auto;" />
For example, the graph above plots the line <span class="math inline">\(\Delta_e=0.4\Delta_c\)</span>, which implies we’re considering <span class="math inline">\(k=0.4\)</span> (recall that the costs are scaled by £1000, so in fact, we mean <span class="math inline">\(k=\)</span>£400!). As is possible to see, most of the points lie <strong>above</strong> the willingness to pay. In other words, it is much more likely that the intervention <span class="math inline">\(t=1\)</span> is <em>not</em> cost-effective. The proportion of points below the line (<a href="https://gianluca.statistica.it/book/bmhe/">BMHE</a> refers to this as the “sustainability area”) is below 0.5 and it indicates, for that given willingness to pay, the CEAC.</p>
<p>In reality, we do not really need to perform the economic evaluation “by hand”, ie programming the code above to compute the various health economic summaries and graphical representations. This is the point of <code>BCEA</code>!… In this case, the output of the <code>BUGS</code> model does contain the population average measures of costs and effectiveness — these are the parameters <code>mu.c</code> and <code>mu.e</code>. We can simply pass these as “input” to <code>bcea</code> and obtain all the necessary and relevant economic summaries and plots. For instance, we can use the following code to create two matrices <code>e</code> and <code>c</code>, which we can then feed to <code>BCEA</code> as input.</p>
<pre class="r"><code># Defines the population average &quot;effectiveness measures&quot; (NB: days in hospital are bad so take -e!)
e = -m2$sims.list$mu.e
# Defines the population average &quot;cost measures&quot;
c = m2$sims.list$mu.c
# Calls BCEA
library(BCEA)
# Runs the function `bcea` to obtain the health economics summary
he=bcea(
  # Defines the inputs
  e,c,
  # Labels for the two intervention groups
  interventions=c(&quot;Standard case management&quot;,&quot;Intensive case management&quot;),
  # Defines the &quot;reference&quot; interventions (the one that is evaluated)
  ref=2,
  # Selects the maximum value for the willingness to pay threshold
  Kmax=1000
)
# Now can summarise the decision problem
summary(he)</code></pre>
<pre><code>NB: k (wtp) is defined in the interval [0 - 1000]

Cost-effectiveness analysis summary 

Reference intervention:  Intensive case management
Comparator intervention: Standard case management

Standard case management dominates for all k in [0 - 1000] 


Analysis for willingness to pay parameter k = 1000

                          Expected utility
Standard case management            -74728
Intensive case management           -81073

                                                          EIB    CEAC    ICER
Intensive case management vs Standard case management -6345.2 0.28222 -0.3973

Optimal intervention (max expected utility) for k = 1000: Standard case management
           
EVPI 1834.8</code></pre>
<pre class="r"><code># Or plot the results
ceplane.plot(he) </code></pre>
<p><img src="/practical/04_ild/solutions_files/figure-html/hebcea-1.png" width="55%" style="display: block; margin: auto;" /></p>
<p><br></p>
</div>
<div id="running-the-model-using-r2jags" class="section level1">
<h1>Running the model using R2jags</h1>
<p>In general, there aren’t many differences in running a model using <code>JAGS</code> or <code>BUGS</code>. In this particular case, however, a “vanilla” run of the code in the file <a href="IPD_analysis.R"><code>IPD_analysis.R</code></a> may give some interesting inconsistency.</p>
<p><div class="alert alert-warning">
  <div>
    You do <strong>NOT</strong> need to run the model using <code>R2jags</code> — this is just so you are aware of the potential issues. Or, of course, in case you <em>are</em> running <code>JAGS</code> and have encountered this first hand!
  </div>
</div>
</p>
<p>The script basically is identical — the only differences are that</p>
<ul>
<li>You load the package <code>R2jags</code> instead of <code>R2OpenBUGS</code>;</li>
<li>You call the function <code>jags</code> instead of the function <code>bugs</code>. Specifically, the call to <code>jags</code> should <strong>not</strong> include the option <code>debug</code>, which is specific to <code>R2OpenBUGS</code>.</li>
</ul>
<p>However, if you run the script and call</p>
<pre class="r"><code>model.file=&quot;normal-mod.txt&quot;
params &lt;- c(&quot;mu&quot;,&quot;ss&quot;,&quot;ls&quot;,&quot;delta.c&quot;,&quot;dev&quot;,&quot;total.dev&quot;)
n.chains=2
n.burnin=1000
n.iter=2000
n.thin=1
m=jags(data=cost.data,inits=NULL,model.file=model.file,parameters.to.save=params,
       n.chains=n.chains,n.iter=n.iter,n.burnin=n.burnin,n.thin=n.thin,DIC=T)</code></pre>
<p>interestingly the summary table looks like this.</p>
<pre class="r"><code>print(m,digits=2)</code></pre>
<pre><code>Inference for Bugs model at &quot;normal-mod.txt&quot;, fit using jags,
 2 chains, each with 2000 iterations (first 1000 discarded)
 n.sims = 2000 iterations saved
           mu.vect sd.vect     2.5%      25%      50%      75%    97.5% Rhat n.eff
delta.c       1.63    9.35   -16.96    -4.54     1.86     7.93    19.73 1.01  2000
dev[1]     3583.82  378.94  2994.04  3200.21  3815.87  3925.86  3934.52 4.76     2
dev[2]     3891.97   67.47  3749.52  3836.38  3928.69  3942.13  3972.89 3.48     3
ls[1]         4.36    0.71     3.07     3.77     4.81     4.98     4.99 3.77     2
ls[2]         4.87    0.10     4.65     4.79     4.93     4.95     5.00 3.46     3
mu[1]        22.70    5.93    10.01    19.78    22.66    25.39    36.14 1.22   110
mu[2]        24.33    7.23    10.15    19.65    24.39    29.46    38.22 1.09   390
ss[1]     12042.81 9274.28   463.50  1888.71 15634.44 21181.73 21746.46 4.19     2
ss[2]     17410.39 3360.54 10968.97 14388.13 19129.83 19906.17 21902.75 3.50     3
total.dev  7475.79  339.34  6924.63  7142.32  7658.96  7760.59  7862.98 3.87     2
deviance   7475.79  339.34  6924.63  7142.32  7658.96  7760.59  7862.98 3.87     2

For each parameter, n.eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor (at convergence, Rhat=1).

DIC info (using the rule, pD = var(deviance)/2)
pD = 16814.4 and DIC = 24290.2
DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
<p>The exact same model, with the exact same data, shows different results with evidence of <strong>very</strong> poor mixing in the chains (high values of <code>Rhat</code> and very low values for <code>n.eff</code>)!</p>
<p>The reason for this is in the different way in which <code>OpenBUGS</code> and <code>JAGS</code> handle the generation of initial values: the former uses a random draw from the prior distribution, while the latter uses values that are restricted to be in the proximity of the mean of the prior distribution<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>.</p>
<p>In this case, <code>R2OpenBUGS</code> does a better job at selecting initial values that are closer to the main mass in the posterior distribution, which means that the
process converges much more easily and quickly. The process can be “saved” either by running the chains for longer, or by selecting “better” initial values. For instance, running the code</p>
<pre class="r"><code>m=jags(data=cost.data,inits=NULL,model.file=model.file,parameters.to.save=params,
       n.chains=n.chains,n.iter=10000,n.burnin=9000,n.thin=n.thin,DIC=T)</code></pre>
<p>(which creates 10000 simulations, discards the first 9000 and thus saves 1000 per chain — or 2000 in total). The summary statistics look <em>much</em> better now:</p>
<pre class="r"><code>print(m,digits=2)</code></pre>
<pre><code>Inference for Bugs model at &quot;normal-mod.txt&quot;, fit using jags,
 2 chains, each with 10000 iterations (first 9000 discarded)
 n.sims = 2000 iterations saved
          mu.vect sd.vect    2.5%     25%     50%     75%   97.5% Rhat n.eff
delta.c      1.90    1.74   -1.53    0.71    1.91    3.03    5.30 1.00   570
dev[1]    2995.58    2.02 2993.68 2994.20 2994.94 2996.28 3000.71 1.01  2000
dev[2]    3064.08    1.86 3062.30 3062.79 3063.55 3064.69 3068.71 1.01  1100
ls[1]        3.09    0.04    3.02    3.07    3.09    3.12    3.17 1.00  2000
ls[2]        3.15    0.04    3.08    3.13    3.15    3.18    3.22 1.01  1500
mu[1]       22.68    1.19   20.34   21.92   22.68   23.48   24.99 1.00   870
mu[2]       24.58    1.25   22.15   23.75   24.57   25.42   27.02 1.00  1200
ss[1]      487.75   37.82  418.52  461.10  485.74  511.92  569.74 1.00  2000
ss[2]      549.30   40.44  476.95  520.62  547.32  577.18  632.35 1.01  1600
total.dev 6059.66    2.75 6056.41 6057.67 6058.93 6060.96 6066.85 1.00  2000
deviance  6059.66    2.75 6056.41 6057.67 6058.93 6060.96 6066.85 1.00  2000

For each parameter, n.eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor (at convergence, Rhat=1).

DIC info (using the rule, pD = var(deviance)/2)
pD = 3.8 and DIC = 6063.5
DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
<p>All the <code>Rhat</code> statistics are below 1.1 and the <code>n.eff</code> values are much closer, in general, to the “nominal” sample size <code>n.sims=2000</code>. Even better, we can pass “reasonable” initial values and ensure even better and quicker convergence. For instance, we could use the files <a href="normal-inits1.txt"><code>normal-initis1.txt</code></a> and <a href="normal-inits2.txt"><code>normal-inits2.txt</code></a>, which can be loaded into the workspace and stored in a <code>list</code> using the following code.</p>
<pre class="r"><code>inits=list(source(&quot;normal-inits1.txt&quot;)$value,source(&quot;normal-inits2.txt&quot;)$value)
inits</code></pre>
<pre><code>## [[1]]
## [[1]]$mu
## [1] 0.316036 1.282370
## 
## [[1]]$ls
## [1] 0.437099 0.493518
## 
## 
## [[2]]
## [[2]]$mu
## [1] 1.73574 1.31659
## 
## [[2]]$ls
## [1] -1.96202 -1.06980</code></pre>
<p>We can run the original model by specifying these</p>
<pre class="r"><code>m=jags(data=cost.data,inits=inits,model.file=model.file,parameters.to.save=params,
       n.chains=n.chains,n.iter=n.iter,n.burnin=n.burnin,n.thin=n.thin,DIC=T)</code></pre>
<p>and see that convergence is <em>not</em> an issue, even with simply <code>n.iter=</code> 2000 total iterations and <code>n.burnin=</code> 1000 discarded as burn-in.</p>
<pre class="r"><code>print(m,digits=2)</code></pre>
<pre><code>Inference for Bugs model at &quot;normal-mod.txt&quot;, fit using jags,
 2 chains, each with 2000 iterations (first 1000 discarded)
 n.sims = 2000 iterations saved
          mu.vect sd.vect    2.5%     25%     50%     75%   97.5% Rhat n.eff
delta.c      1.92    1.73   -1.39    0.75    1.94    3.07    5.33 1.00  2000
dev[1]    2995.61    2.03 2993.67 2994.16 2994.98 2996.31 3001.05 1.00  2000
dev[2]    3064.19    1.84 3062.30 3062.85 3063.58 3065.00 3068.91 1.00  1400
ls[1]        3.09    0.04    3.02    3.07    3.09    3.12    3.17 1.01   210
ls[2]        3.15    0.04    3.08    3.13    3.15    3.18    3.23 1.00   810
mu[1]       22.65    1.20   20.22   21.85   22.63   23.43   25.01 1.00  1100
mu[2]       24.57    1.26   22.12   23.73   24.60   25.43   27.06 1.00  2000
ss[1]      486.70   37.71  418.45  461.68  484.59  510.23  568.02 1.01   210
ss[2]      551.06   42.28  473.12  520.73  549.09  578.76  641.82 1.00   820
total.dev 6059.79    2.67 6056.44 6057.71 6059.21 6061.27 6066.09 1.00  1400
deviance  6059.79    2.67 6056.44 6057.71 6059.21 6061.27 6066.09 1.00  1400

For each parameter, n.eff is a crude measure of effective sample size,
and Rhat is the potential scale reduction factor (at convergence, Rhat=1).

DIC info (using the rule, pD = var(deviance)/2)
pD = 3.6 and DIC = 6063.3
DIC is an estimate of expected predictive error (lower deviance is better).</code></pre>
</div>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p>The <a href="https://sourceforge.net/projects/mcmc-jags/files/Manuals/4.x/jags_user_manual.pdf/download"><code>JAGS</code> manual</a> states on page 16 that “<em>initial values are not supplied by the user, then each parameter chooses its own initial value based on the values of its parents. The initial value is chosen to be a ‘typical value’ from the prior distribution. The exact meaning of ‘typical value’ depends on the distribution of the stochastic node, but is usually the mean, median, or mode</em>”<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>

          </div>

          



          
          
          <div class="article-widget">
            
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/practical/04_ild/tutorial-regression/" rel="next">Linear regression Tutorial</a>
  </div>
  
  
</div>

          </div>
          
        </div>

        <div class="body-footer">
          
          

          


          
          
          
          
          


          




          




        </div>

      </article>

      <footer class="site-footer">
  

  <p class="powered-by">
    
    
      &copy;  2022-2024 &middot;

    Based on
    <a href="https://wowchemy.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Wowchemy</a>
    
    
    (version 5.3.0)
    
    for <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a> &middot;
    
    
    <i><b>Latest update: 23 Jun 2022 </i></b>
    

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>

</footer>


    </main>
  </div>
</div>

  </div>

  <div class="page-footer">
    
    
  </div>

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

      

    
    <script src="/js/vendor-bundle.min.b73dfaac3b6499dc997741748a7c3fe2.js"></script>

    
    
    
      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/highlight.min.js" integrity="sha512-TDKKr+IvoqZnPzc3l35hdjpHD0m+b2EC2SrLEgKDRWpxf2rFCxemkgvJ5kfU48ip+Y+m2XVKyOCD85ybtlZDmw==" crossorigin="anonymous"></script>
        
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/r.min.js" crossorigin="anonymous"></script>
        
      

    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.js" integrity="sha512-SeiQaaDh73yrb56sTW/RgVdi/mMqNeM2oBwubFHagc5BkixSpP1fvqF47mKzPGWYSSy4RwbBunrJBQ4Co8fRWA==" crossorigin="anonymous"></script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js" integrity="sha512-I7w3ZdSFzw5j3jU3ZkNikBNeIrl3i+hEuEdwNmqUJvwNcaBUNcijnP2gd9DtGlgVYDplfjGoD8vTNsID+lCjqg==" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    

    
    

    
    
    
    

    
    

    
    
    
    
    
    
    
    
    
    <script src="/en/js/wowchemy.min.50d3bf3df0c53b31631bb48a62b35f92.js"></script>

    






</body>
</html>
